# Generated by Django 4.1.3 on 2023-02-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactuslog',
            name='client_name',
        ),
        migrations.AddField(
            model_name='orders',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
