# Generated by Django 4.1.3 on 2023-02-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0002_remove_contactuslog_client_name_orders_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuslog',
            name='client_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
