# Generated by Django 4.1.7 on 2023-02-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0003_contactuslog_client_resolved'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_time', models.DateTimeField(auto_now_add=True)),
                ('store_id', models.CharField(blank=True, max_length=36, null=True)),
                ('order_id', models.CharField(blank=True, max_length=36, null=True)),
                ('client_email', models.CharField(max_length=100, null=True)),
                ('cancel_reason', models.TextField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'cancel_order_log',
                'managed': True,
            },
        ),
    ]
