# Generated by Django 4.1.5 on 2023-03-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0004_cancelorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelorder',
            name='other_reason',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menus',
            name='availbility',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
